### ISSUE TITLE
Social Icon for GitLab

### ISSUE THREAD

**Issue by MatthiasLohr** [ColorlibHQ/Sparkling#225]
Hello,

can you please add a social icon for GitLab? Icon is included in FontAwesome: https://fontawesome.com/icons/gitlab?style=brands

Best regards
Matthias

**Comment by MatthiasLohr** [comment]
@cristianraiber Btw, is https://github.com/MachoThemes/Sparkling/ a good point for forking and creating pull requests (instead of having pull requests discarded here)?

**Comment by cristianraiber** [comment]
@MatthiasLohr yep :) fork from MachoThemes/Sparkling and do a pull request there. All pull requests merged there will be merged into puikinish/Sparkling once tested and ready.

**Comment by MatthiasLohr** [comment]
Thx!

Color for GitLab could be #fc9403
