### ISSUE TITLE
Optimizations for Google Page Speed

### ISSUE THREAD

**Issue by MatthiasLohr** [ColorlibHQ/Sparkling#226]
Hello,

I just used the Google Page Speed Tool (https://developers.google.com/speed/pagespeed/insights/) to analyze my Sparkling based website. Basically, the tool suggests to think about loading JS/CSS resources asynchronously.
For which resources do you think that could work? Is there any JavaScript used for the generation of the page i did not see? For me, disabling JavaScript for the page worked fine to get the landing page loaded and displayed without any errors.

What do you think about that?

Best regards
Matthias

**Comment by cristianraiber** [comment]
Hi @MatthiasLohr - I recommend using https://wordpress.org/plugins/autoptimize/. Also, GPSI isn't reliable: https://aristotlebuzz.com/if-youre-not-a-developer-stop-using-googles-pagespeed-test/

**Comment by MatthiasLohr** [comment]
Sounds great and might be a valid solution, but what do you think about doing (some?) optimizations directly in the template code? This would push the need for such a plugin - and every plugin seems to be a bit of overhead and downgrade performance a bit - to a later point in time.

P.S.: This is not a feature request, but a first discussion about the reasons for doing (or not doing) it.
