### ISSUE TITLE
Feature discussion: Link icons

### ISSUE THREAD

**Issue by MatthiasLohr** [ColorlibHQ/Sparkling#227]
Hello,

i wanted to start a discussion about link icons. E.g. i added some affliate links to Amazon on my blog, but i wanted the user to see, that's an Amazon link before clicking. So i used the FontAwesome to add the Amazon icon to the link text. An example for that is here: https://mlohr.com/tag/yubikey/

The question is, if it would be a good idea to add a list of (individual configurable?) standard link icons like Amazon, YouTube, Wikipedia, ...

What do you think about that?

Best regards
Matthias

**Comment by cristianraiber** [comment]
@MatthiasLohr - this seems like a really specific use-case. While I personally believe it's a good idea, I'm not sure that there are many people who would benefit from something like this. 

Let's leave this open and see if anyone pitches in down the road. That might tell us if they're more people interested in something like this or not.

**Comment by mahendrapratap4022** [comment]
I agree with @cristeacosmin its sounds very specific use-case. Also, nobody has reacted to it yet for years so I'm closing it and let me know if you think it should be open.
