### ISSUE TITLE
Menu hover not functions normally

### ISSUE THREAD

**Issue by nodarik** [ColorlibHQ/Sparkling#230]
here is how to replicate it:
ope this https://colorlib.com/sparkling/
in a normal window size, you can hover on about us and submenu will appear, but if you resize window under 1028px then hover does not work and you must click on the rectangle on the right side of the about menu, 

The ticket where this problem reported:
https://colorlib.com/wp/forums/topic/menu-wrap/

**Comment by mahendrapratap4022** [comment]
Hi @nodarik it is fixed in https://github.com/ColorlibHQ/Sparkling/pull/258
Thanks
