### ISSUE TITLE
Dropdown caret location broken on upgrade

### ISSUE THREAD

**Issue by pjrobertson** [ColorlibHQ/Sparkling#236]
After upgrading from Sparkling 2.3.3 to 2.4.4, the main issue was with the location of the dropdown caret.

After upgrading to 2.4.4, wrong:

![screenshot 2019-02-02 at 16 45 14](https://user-images.githubusercontent.com/150431/52162112-f596cb00-2709-11e9-9c8d-5b1cdbfaa911.png)

Before upgrading (using 2.3.3), correct:

![screenshot 2019-02-02 at 16 45 49](https://user-images.githubusercontent.com/150431/52162118-08a99b00-270a-11e9-851a-fc9959f24e29.png)

I did some debugging and it seems the problem comes from [this commit and change](https://github.com/ColorlibHQ/Sparkling/commit/907dc4317ca719adaeff66a01c3502292c090e05#diff-08372ea3f7b4505661f147506d53c0fcR117) which was done to fix #151. The change was to put the `<span>` tag outside of the `<a>` tag). I can confirm that this fixes the issue raised in #151, but we need to find a solution to avoid the issue I am seeing.

**Comment by pjrobertson** [comment]
Actually, I can confirm that on my website, even after this change dropdown links do not work on mobile. This is a separate issue

**Comment by cristianraiber** [comment]
@pjrobertson - this PR should fix your issue: https://github.com/ColorlibHQ/Sparkling/pull/237

If you want to give it a test-drive before we release it on w.org (might take a while for it to hit the w.org servers) we'd appreciate it!

Thanks,
Cristian.

**Comment by pjrobertson** [comment]
Wow, that's amazingly quick Raiber! Please find off from merging until next
week. I am currently away from my computer traveling. I aim to review it by
13th Feb (1 week)

**Comment by mahendrapratap4022** [comment]
Hi @pjrobertson The fix is added in https://github.com/ColorlibHQ/Sparkling/pull/253
