### ISSUE TITLE
Getting started broken cols

### ISSUE THREAD

**Issue by razvanaldea89** [ColorlibHQ/Sparkling#238]
![sparkling getting started cols](https://user-images.githubusercontent.com/44024114/63326018-09b3ba00-c334-11e9-8014-14dae486f6d8.PNG)

Steps should be in 3 columns

**Comment by mahendrapratap4022** [comment]
Hi @razvanaldea89 it is fixed in https://github.com/ColorlibHQ/Sparkling/pull/253
Thanks
