### ISSUE TITLE
Topnav Menu CSS broken in IE and Edge

### ISSUE THREAD

**Issue by laurenay** [ColorlibHQ/Sparkling#243]
Hello
Because :focus-within is a pseudo class that IE and Edge doesn’t understand it ignores the entire rule block so the topant menu is broken. In my child theme I have splited the rules into two blocks so Edge and IE only ignore the block it doesn’t understand. Now my website is working in IE and Edge, but the theme should be updated.

**Comment by cristianraiber** [comment]
@laurenay - are you using the Chrome-based Edge ?

**Comment by laurenay** [comment]
@cristianraiber of course not ! I did my tests with the most used to make my website compatible with as many users as possible.

**Comment by cristianraiber** [comment]
@laurenay - please test with the Chromium-based EDGE browser as that will replace ALL existing IE/EDGE versions in the really short term future. And that is the one we will be also supporting.

**Comment by laurenay** [comment]
@cristianraiber I already know that's work. It's an issue on old browsers.

**Comment by cristianraiber** [comment]
Not really an issue as those browsers will get replaced with the new browser, based on Chromium. We will release an update though to address this issue as upgrade from old to new browser will take quite a bit of time to get up to date.

**Comment by cristianraiber** [comment]
@razvanaldea89 - when you get to this, please issue a patch for this.

**Comment by mahendrapratap4022** [comment]
Hi @laurenay it is fixed in https://github.com/ColorlibHQ/Sparkling/pull/253
