### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by adriansuter** [ColorlibHQ/Sparkling#244]
Hi there

The following texts do not have a translation (neither in the `.pot` file nor in the `.po` files).
- `One thought to &ldquo;%s&rdquo;`
- `%1$s thought to &ldquo;%2$s&rdquo;`
- `%1$s thoughts to &ldquo;%2$s&rdquo;`

See for example
https://github.com/ColorlibHQ/Sparkling/blob/5590eb65b83f75223e2a3e72f9449c41a9ff785f/comments.php#L30-L46

The `.pot` file contains only
https://github.com/ColorlibHQ/Sparkling/blob/5590eb65b83f75223e2a3e72f9449c41a9ff785f/languages/sparkling.pot#L57-L63

Note that in the source code you have "...**to**..." while the `pot`-file has "...**on**..".

**Comment by mahendrapratap4022** [comment]
Hi @adriansuter It is fixed in https://github.com/ColorlibHQ/Sparkling/pull/259
Thanks
