### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by puikinsh** [ColorlibHQ/Sparkling#247]
https://wordpress.org/support/topic/php-8-not-compatible/

**Comment by mushfiqur-rahman** [comment]
> https://wordpress.org/support/topic/php-8-not-compatible/

I'm facing the same problem. Did you get any solution for it?

**Comment by mahendrapratap4022** [comment]
Hi @puikinsh PHP 8 support is added in https://github.com/ColorlibHQ/Sparkling/pull/253
The updated version of Sparkling is 3.0 now  ✨🍾
