### ISSUE TITLE
Tabs are not working

### ISSUE THREAD

**Issue by nodarik** [ColorlibHQ/Sparkling#248]
In the latest version of the theme 2.4.8  tabs are not working, https://prnt.sc/y07ywj

https://forums.colorlib.com/t/update-to-2-4-8-bootstrap-problem/27594/4?u=colorlibsupport

**Comment by mahendrapratap4022** [comment]
Hi @nodarik issue is fixed in https://github.com/ColorlibHQ/Sparkling/pull/253
Thanks
