### ISSUE TITLE
Optimize Responsive Design

### ISSUE THREAD

**Issue by LTribelhorn** [ColorlibHQ/Sparkling#251]
Hi
Today most screens (on desktop) are bigger than 1200px. But because this is defined as the largest device size in bootstrap.css, there is far too much whitespace left and right of the content (.container) on larger screens.

I would suggest adding an additional breakpoint at 1900px:
```
@media (min-width: 1900px) {
  .container {
    width: 1370px;
  }
}
```

Of course, there might be additional things in the design which would need to be optimized for the new breakpoint. I don't know the theme enough to provide all code changes here.
If you prefer to add it at some other point, that’s fine with me as well. I would just really appreciate if there was anything above 1200px.

Thanks!

**Comment by mahendrapratap4022** [comment]
Hi @LTribelhorn I have added you request in https://github.com/ColorlibHQ/Sparkling/pull/256
Thanks.
